Repository capo-project/capo-backend, pull requests merged in 2025-01, with the labels that each got.

#22 ♻️ 코드 리팩토링 : AWS S3 로직 리팩토링 - 인터페이스 기반 구조 개선
  src/main/java/com/realworld/application/file/dto/FileMetaData.java
  src/main/java/com/realworld/application/file/port/FileStorage.java
  src/main/java/com/realworld/common/holder/uuid/UUIDHolder.java
  src/main/java/com/realworld/common/holder/uuid/UUIDHolderImpl.java
  src/main/java/com/realworld/infrastructure/cloud/CloudFileStorage.java
  src/main/java/com/realworld/infrastructure/cloud/aws/AwsS3Handler.java
  src/main/java/com/realworld/infrastructure/cloud/aws/AwsS3HandlerImpl.java
  src/main/java/com/realworld/v1/feature/file/service/CloudStorageService.java
  src/main/java/com/realworld/v1/infra/aws/AwsServiceV1.java
  src/test/java/com/realworld/infrastructure/cloud/aws/AwsS3HandlerImplTest.java
Labels: 🛠️ Refactor

#23 refactor : v2 불변 코드 final 키워드 추가 및 에러 코드 이름 변경
  src/main/java/com/realworld/application/auth/mail/port/AuthMailRepository.java
  src/main/java/com/realworld/application/auth/mail/service/AuthMailService.java
  src/main/java/com/realworld/application/auth/mail/service/AuthMailServiceImpl.java
  src/main/java/com/realworld/feature/auth/mail/entity/AuthMail.java
  src/main/java/com/realworld/infrastructure/mail/SmtpMailSender.java
  src/main/java/com/realworld/infrastructure/persistence/auth/mail/repository/AuthMailRepositoryImpl.java
  src/main/java/com/realworld/v1/feature/auth/AuthControllerV1.java
  src/main/java/com/realworld/v1/feature/auth/mail/AuthMailServiceV1Impl.java
  src/main/java/com/realworld/v1/global/code/ErrorCode.java
  src/main/java/com/realworld/v1/global/config/exception/CustomAuthMailExceptionHandler.java
  src/main/java/com/realworld/v1/global/config/exception/GlobalExceptionHandler.java
  src/main/java/com/realworld/web/auth/mail/controller/AuthController.java
  src/main/java/com/realworld/web/auth/mail/payload/request/AuthMailRequest.java
  src/test/java/com/realworld/feature/auth/mail/domain/mail/AuthMailTest.java
Labels: 🛠️ Refactor

#25 📚 docs : 포토카드 회원, 프로필 모델링
  README.md
Labels: 📖 Docs

#26 ♻️ 코드 리팩토링 : 파일 관리 기능 강화 및 구조 개선
  src/main/java/com/realworld/application/file/port/FileStorage.java
  src/main/java/com/realworld/application/file/port/ImageResizer.java
  src/main/java/com/realworld/application/file/service/FileService.java
  src/main/java/com/realworld/application/file/service/FileServiceImpl.java
  src/main/java/com/realworld/common/config/aws/S3Config.java
  src/main/java/com/realworld/common/exception/CustomFileExceptionHandler.java
  src/main/java/com/realworld/common/exception/CustomImageExceptionHandler.java
  src/main/java/com/realworld/common/holder/uuid/UUIDGeneratorHolderImpl.java
  src/main/java/com/realworld/common/holder/uuid/UUIDHolder.java
  src/main/java/com/realworld/common/holder/uuid/UUIDHolderImpl.java
  src/main/java/com/realworld/common/response/code/ExceptionResponseCode.java
  src/main/java/com/realworld/common/type/file/FileFormat.java
  src/main/java/com/realworld/feature/file/File.java
  src/main/java/com/realworld/feature/file/FileDetails.java
  src/main/java/com/realworld/feature/file/FileMetaData.java
  src/main/java/com/realworld/infrastructure/cloud/CloudFileStorage.java
  src/main/java/com/realworld/infrastructure/cloud/aws/AwsS3Handler.java
  src/main/java/com/realworld/infrastructure/cloud/aws/AwsS3HandlerImpl.java
  src/main/java/com/realworld/infrastructure/image/ImageResizerHandlerImpl.java
  src/main/java/com/realworld/infrastructure/image/ResizedImage.java
  src/main/java/com/realworld/v1/feature/file/controller/FileControllerV1.java
  src/main/java/com/realworld/v1/feature/file/controller/FileResponseV1.java
  src/main/java/com/realworld/v1/feature/file/domain/FileV1.java
  src/main/java/com/realworld/v1/feature/file/entity/FileJpaEntity.java
  src/main/java/com/realworld/v1/feature/file/service/CloudStorageService.java
  src/main/java/com/realworld/v1/feature/file/service/FileQueryService.java
  src/main/java/com/realworld/v1/feature/file/service/FileQueryServiceImpl.java
  src/main/java/com/realworld/v1/feature/file/service/LocalStorageService.java
  src/main/java/com/realworld/v1/feature/file/service/StorageService.java
  src/main/java/com/realworld/v1/feature/member/domain/Member.java
  src/main/java/com/realworld/v1/feature/member/entity/MemberJpaEntity.java
  src/main/java/com/realworld/v1/feature/member/service/MemberCommandServiceImpl.java
  src/main/java/com/realworld/v1/feature/product/controller/ProductController.java
  src/main/java/com/realworld/v1/feature/product/controller/response/ProductUpdateResponse.java
  src/main/java/com/realworld/v1/feature/profile/controller/ProfileController.java
  src/main/java/com/realworld/v1/feature/profile/service/ProfileCommandService.java
  src/main/java/com/realworld/v1/feature/profile/service/ProfileCommandServiceImpl.java
  src/main/java/com/realworld/v1/feature/temporarily_product/controller/TemporarilyProductController.java
  src/main/java/com/realworld/v1/feature/temporarily_product/controller/response/TemporarilyProductDetailsResponse.java
  src/main/java/com/realworld/v1/feature/temporarily_product/controller/response/TemporarilyProductUpdateResponse.java
  src/main/java/com/realworld/v1/global/config/exception/GlobalExceptionHandler.java
  src/main/java/com/realworld/v1/global/utils/FileUtil.java
  src/main/java/com/realworld/v1/infra/aws/AwsServiceV1.java
  src/main/java/com/realworld/web/file/controller/FileController.java
  src/main/java/com/realworld/web/file/payload/request/FileDeleteRequest.java
  src/main/java/com/realworld/web/file/payload/request/FileMoveRequest.java
  src/main/java/com/realworld/web/file/payload/response/FileResponse.java
  src/main/java/com/realworld/web/file/payload/response/FileResponses.java
  src/main/java/com/realworld/web/file/payload/response/FileUrlResponses.java
  src/test/java/com/realworld/feature/file/mock/MockFileData.java
  src/test/java/com/realworld/infrastructure/cloud/aws/AwsS3HandlerImplTest.java
Labels: 🛠️ Refactor

#32 ♻️ 리팩토링 : v2 Jwt Security 리팩토링 완료
  src/main/java/com/realworld/application/auth/jwt/port/TokenRepository.java
  src/main/java/com/realworld/application/auth/jwt/service/JwtService.java
  src/main/java/com/realworld/application/auth/jwt/service/JwtServiceImpl.java
  src/main/java/com/realworld/application/auth/jwt/service/UserDetailServiceImpl.java
  src/main/java/com/realworld/application/member/port/MemberRepository.java
  src/main/java/com/realworld/application/member/service/MemberService.java
  src/main/java/com/realworld/application/member/service/MemberServiceImpl.java
  src/main/java/com/realworld/common/config/security/JwtAccessDeniedFilter.java
  src/main/java/com/realworld/common/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/realworld/common/config/security/JwtAuthenticationFilter.java
  src/main/java/com/realworld/common/config/security/SecurityConfig.java
  src/main/java/com/realworld/common/holder/jwt/JwtProviderHolder.java
  src/main/java/com/realworld/common/response/code/ExceptionResponseCode.java
  src/main/java/com/realworld/common/type/jwt/Authority.java
  src/main/java/com/realworld/common/type/jwt/JwtHeaderStatus.java
  src/main/java/com/realworld/common/type/jwt/TokenStatus.java
  src/main/java/com/realworld/feature/auth/jwt/CustomUserDetails.java
  src/main/java/com/realworld/feature/auth/jwt/Token.java
  src/main/java/com/realworld/infrastructure/jwt/handler/JwtTokenHandler.java
  src/main/java/com/realworld/infrastructure/jwt/handler/JwtTokenHandlerImpl.java
  src/main/java/com/realworld/infrastructure/persistence/jwt/TokenRedisRepository.java
  src/main/java/com/realworld/infrastructure/persistence/jwt/TokenRepositoryImpl.java
  src/main/java/com/realworld/infrastructure/persistence/member/MemberRepositoryImpl.java
  src/main/java/com/realworld/v1/feature/auth/AuthService.java
  src/main/java/com/realworld/v1/feature/loginout/LoginOutControllerV1.java
  src/main/java/com/realworld/v1/feature/loginout/LoginServiceImpl.java
  src/main/java/com/realworld/v1/feature/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/realworld/v1/feature/token/repository/TokenRepositoryV1.java
  src/main/java/com/realworld/v1/feature/token/repository/TokenRepositoryV1Impl.java
  src/main/java/com/realworld/v1/feature/token/service/TokenCommandServiceImpl.java
  src/main/java/com/realworld/v1/feature/token/service/TokenQueryServiceImpl.java
  src/main/java/com/realworld/v1/global/config/SecurityConfigV1.java
  src/main/java/com/realworld/v1/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/realworld/v1/global/config/jwt/JwtSecurityConfig.java
  src/main/java/com/realworld/v1/global/config/jwt/JwtTokenProviderV1.java
  src/main/java/com/realworld/web/member/controller/LoginOutController.java
  src/main/java/com/realworld/web/member/controller/MemberController.java
  src/main/java/com/realworld/web/member/controller/SignUpController.java
  src/main/java/com/realworld/web/member/payload/response/LoginResponse.java
Labels: 🛠️ Refactor

#35 ✅ 테스트 추가 : 파일 메타데이터 유효성 검증 및 통합 테스트 추가
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/realworld/application/file/service/FileServiceImpl.java
  src/main/java/com/realworld/feature/file/entity/FileMetaData.java
  src/test/java/com/realworld/application/file/service/FileServiceImplTest.java
  src/test/java/com/realworld/feature/file/domain/FileDetailsTest.java
  src/test/java/com/realworld/feature/file/domain/FileMetaDataTest.java
  src/test/java/com/realworld/feature/file/domain/FileTest.java
  src/test/java/com/realworld/infrastructure/cloud/aws/AwsS3HandlerImplTest.java
  src/test/java/com/realworld/infrastructure/cloud/aws/mock/AwsS3HandlerMockTest.java
  src/test/java/com/realworld/infrastructure/cloud/aws/mock/testcontainers/AwsS3HandlerTestContainersTest.java
Labels: ☔️ Test

#36 코드 리팩토링 : Spring Security 구현 완료, 테스트 코드 제외 완료 (추후 작업)
  README.md
  src/main/java/com/realworld/application/auth/jwt/port/TokenRepository.java
  src/main/java/com/realworld/application/auth/jwt/service/JwtService.java
  src/main/java/com/realworld/application/auth/jwt/service/JwtServiceImpl.java
  src/main/java/com/realworld/application/auth/jwt/service/UserDetailServiceImpl.java
  src/main/java/com/realworld/application/member/service/member/MemberService.java
  src/main/java/com/realworld/application/member/service/member/MemberServiceImpl.java
  src/main/java/com/realworld/common/config/security/JwtAuthenticationFilter.java
  src/main/java/com/realworld/common/config/security/SecurityConfig.java
  src/main/java/com/realworld/common/holder/jwt/JwtProviderHolder.java
  src/main/java/com/realworld/feature/auth/jwt/Token.java
  src/main/java/com/realworld/feature/member/entity/Member.java
  src/main/java/com/realworld/infrastructure/jwt/handler/JwtTokenHandler.java
  src/main/java/com/realworld/infrastructure/jwt/handler/JwtTokenHandlerImpl.java
  src/main/java/com/realworld/infrastructure/persistence/jwt/TokenRedisRepository.java
  src/main/java/com/realworld/infrastructure/persistence/jwt/TokenRepositoryImpl.java
  src/main/java/com/realworld/web/member/controller/LoginOutController.java
  src/main/java/com/realworld/web/member/controller/SignUpController.java
  src/main/java/com/realworld/web/member/payload/request/LoginRequest.java
  src/main/java/com/realworld/web/member/payload/response/LoginResponse.java
  src/main/resources/application.yml
  src/test/java/com/realworld/infrastructure/persistence/jwt/TokenRepositoryImplTest.java
Labels: 🛠️ Refactor

#37 ✅ 테스트 추가 : ResizedImage 및 ImageResizerHandlerImpl 리팩토링 및 단위 테스트 추가
  build.gradle
  src/main/java/com/realworld/application/file/port/ImageResizer.java
  src/main/java/com/realworld/common/response/code/ExceptionResponseCode.java
  src/main/java/com/realworld/infrastructure/image/ImageResizerHandlerImpl.java
  src/test/java/com/realworld/feature/file/domain/FileMetaDataTest.java
  src/test/java/com/realworld/infrastructure/image/ImageResizerHandlerImplTest.java
  src/test/java/com/realworld/infrastructure/image/ResizedImageTest.java
Labels: ☔️ Test

#38 ✅ 테스트 수정 : 파일 도메인 기능 테스트 명명 수정 및 MockFileData 구조 수정
  build.gradle
  src/main/java/com/realworld/application/file/service/FileService.java
  src/main/java/com/realworld/application/file/service/FileServiceImpl.java
  src/main/java/com/realworld/common/config/aws/AwsS3Config.java
  src/main/java/com/realworld/feature/file/entity/FileMetaData.java
  src/main/java/com/realworld/web/file/controller/FileController.java
  src/main/resources/application.yml
  src/test/java/com/realworld/common/localstack/TestLocalStackConfig.java
  src/test/java/com/realworld/feature/file/domain/FileDetailsTest.java
  src/test/java/com/realworld/feature/file/domain/FileMetaDataTest.java
  src/test/java/com/realworld/feature/file/domain/FileTest.java
  src/test/java/com/realworld/feature/file/mock/MockFileData.java
  src/test/java/com/realworld/infrastructure/cloud/aws/AwsS3HandlerImplTest.java
  src/test/java/com/realworld/infrastructure/cloud/aws/mock/AwsS3HandlerMockTest.java
  src/test/java/com/realworld/infrastructure/cloud/aws/mock/testcontainers/AwsS3HandlerTestContainersTest.java
Labels: ☔️ Test

#40 Dev/v2 member
  build.gradle
  src/main/java/com/realworld/application/auth/jwt/service/JwtService.java
  src/main/java/com/realworld/application/auth/jwt/service/JwtServiceImpl.java
  src/main/java/com/realworld/application/member/port/MemberRepository.java
  src/main/java/com/realworld/common/config/security/JwtAuthenticationFilter.java
  src/main/java/com/realworld/common/config/security/SecurityConfig.java
  src/main/java/com/realworld/infrastructure/jwt/handler/JwtTokenHandler.java
  src/main/java/com/realworld/infrastructure/persistence/member/MemberRepositoryImpl.java
  src/main/java/com/realworld/web/member/controller/MemberController.java
  src/main/java/com/realworld/web/member/controller/SignUpController.java
  src/main/java/com/realworld/web/member/payload/response/MemberFindResponse.java
  src/main/java/com/realworld/web/member/payload/response/SignUpResponse.java
  src/test/java/com/realworld/application/auth/jwt/service/JwtServiceImplTest.java
  src/test/java/com/realworld/feature/auth/jwt/mock/MockJwtData.java
  src/test/java/com/realworld/feature/auth/mail/domain/mail/AuthMailTest.java
  src/test/java/com/realworld/feature/auth/mail/mock/mail/MockMailData.java
  src/test/java/com/realworld/infrastructure/persistence/auth/mail/repository/AuthMailRepositoryImplTest.java
  src/test/java/com/realworld/infrastructure/persistence/jwt/TokenRepositoryImplTest.java
Labels: 🛠️ Refactor

#41 💚 CI 빌드 수정 : SonarQube --info 제거
  .github/workflows/custom.yml
  build.gradle
Labels: 👷 Chore

#42 ♻️ 코드 리팩토링 : File, Image, AWS과 관련된 클래스 파라미터 final 명시
  src/main/java/com/realworld/application/file/service/FileServiceImpl.java
  src/main/java/com/realworld/feature/file/entity/File.java
  src/main/java/com/realworld/feature/file/entity/FileDetails.java
  src/main/java/com/realworld/feature/file/entity/FileMetaData.java
  src/main/java/com/realworld/infrastructure/cloud/CloudFileStorage.java
  src/main/java/com/realworld/infrastructure/cloud/aws/AwsS3HandlerImpl.java
  src/main/java/com/realworld/infrastructure/image/ImageResizerHandlerImpl.java
  src/main/java/com/realworld/infrastructure/image/ResizedImage.java
  src/test/java/com/realworld/application/file/service/FileServiceImplTest.java
Labels: 🛠️ Refactor
